name: craftd_widget
description: A Server Driven UI library provided by CodandoTV.
version: 1.0.0
homepage: https://github.com/CodandoTV/CraftD

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material: ^1.0.0+2
  dio: ^5.4.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-SemiBold.ttf
        - asset: fonts/Roboto-SemiBoldItalic.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
